package com.ride.authservice.service;

import com.ride.authservice.dto.LoginResponse;

/**
 * Service interface for handling OAuth2 authentication with Keycloak and Google.
 * Provides methods for generating Google login URLs and exchanging authorization codes for tokens.
 */
public interface KeycloakOAuth2AdminServiceApp {

    /**
     * Generates the Google login URL for mobile clients using PKCE.
     *
     * @param codeChallenge The PKCE code challenge generated by the client.
     * @param redirectUri The redirect URI to which the user will be redirected after authentication.
     * @param state The state parameter for CSRF protection (generated by the client).
     * @return The Google login URL for initiating the authentication process.
     */
    String getGoogleLoginUrlForMobile(String codeChallenge, String redirectUri, String state);

    /**
     * Exchanges the authorization code for tokens using PKCE for mobile clients.
     *
     * @param code The authorization code received from Google after user authentication.
     * @param codeVerifier The PKCE code verifier used to validate the code challenge.
     * @param redirectUri The redirect URI used during the authentication process.
     * @return A `LoginResponse` object containing the authentication tokens.
     */
    LoginResponse exchangeGoogleCodeForTokenMobile(String code, String codeVerifier, String redirectUri);
}