package com.ride.authservice.controller;

import com.ride.authservice.dto.LoginResponse;
import com.ride.authservice.service.KeycloakOAuth2AdminServiceApp;
import com.ride.authservice.util.PKCEUtil;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * REST controller for handling mobile OAuth2 authentication flows.
 * Provides endpoints for initiating Google login and handling callbacks.
 */
@AllArgsConstructor
@RestController
@RequestMapping("/api")
public class MobileAuthController {
    private final KeycloakOAuth2AdminServiceApp keycloakAdminService;

    /**
     * Generates the Google authorization URL for mobile clients using PKCE.
     * The client should redirect the user to this URL to initiate the login flow.
     *
     * @param codeVerifier A random string generated by the client (43-128 characters)
     * @param redirectUri The callback URI where the user will be redirected after authentication
     * @return A map containing the authorization URL and state parameter (client must store state for validation)
     */
    @GetMapping("/login/google/mobile")
    public Map<String, String> getGoogleLoginUrlForMobile(
            @RequestParam String codeVerifier,
            @RequestParam String redirectUri
    ) {
        String codeChallenge = PKCEUtil.generateCodeChallenge(codeVerifier);
        String state = PKCEUtil.generateState();
        String authUrl = keycloakAdminService.getGoogleLoginUrlForMobile(codeChallenge, redirectUri, state);
        return Map.of(
                "authorizationUrl", authUrl,
                "state", state
        );
    }

    /**
     * Handles the OAuth2 callback and exchanges the authorization code for tokens.
     * After the user completes authentication, call this endpoint with the received code.
     *
     * IMPORTANT: The state parameter validation should be done by the CLIENT before calling this endpoint.
     * The client receives both 'code' and 'state' from Keycloak's redirect, validates the state matches
     * what was originally sent, and then calls this endpoint to exchange the code for tokens.
     *
     * @param code The authorization code received from Keycloak after successful authentication
     * @param codeVerifier The same code verifier used in the initial authorization request
     * @param redirectUri The same redirect URI used in the initial authorization request
     * @return LoginResponse containing access token, refresh token, and other authentication details
     */
    @PostMapping("/google/callback/mobile")
    public LoginResponse handleGoogleCallbackMobile(
            @RequestParam String code,
            @RequestParam String codeVerifier,
            @RequestParam String redirectUri
    ) {

        return keycloakAdminService.exchangeGoogleCodeForTokenMobile(code, codeVerifier, redirectUri);
    }

}
